Client:
  - any: ['lib/aoi.js/v7/src/structures/Client.ts', 'lib/aoi.js/v7/src/functions/discord/client/*']
  
Classes: 
  - lib/aoi.js/v7/src/structures/*
  
Manager:
  - lib/aoi.js/v7/src/manager/*

Core:
  - lib/aoi.js/v7/src/core/**/*

Functions:Discord: 
  - lib/aoi.js/v7/src/functions/discord/**/*

Functions:JS:
  - lib/aoi.js/v7/src/functions/js/**/*

