name: "🚀 Prettier Check and Write"

on:
  push:

jobs:
  pretty:
    name: "🎨 Run Prettier"
    runs-on: ubuntu-latest

    steps:
      - name: "📂 Checkout Code"
        uses: actions/checkout@v2

      - name: "⚙️ Setup Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: "21"

      - name: "📦 Install Pnpm"
        run: sudo npm i -g pnpm

      - name: "📦 Install Dependencies"
        run: pnpm install --no-frozen-lockfile

      - name: "✍️ Run Prettier Write"
        run: pnpm run pretty:write
